### ISSUE TITLE
Compile error in esp32

### ISSUE THREAD

**Issue by chcmq** [lvgl/lv_lib_rlottie#2]
* Framework Arduino
* Build tool PlatformIO

**So what else do I need to configure？** 

![选区_040](https://user-images.githubusercontent.com/30547484/111864606-f861e200-899c-11eb-888e-3faf238a02a0.png)

**Comment by kisvegabor** [comment]
At this moment the library can be built only with CMake.

@ValentiWorkLearning do you see any chance the make it work with managed builds too?

**Comment by ValentiWorkLearning** [comment]
@kisvegabor hmm. I'll take a look tomorrow.
@chcmq which platform has been used for your building?

**Comment by ajsb85** [comment]
Hi, I want to contribute.

https://github.com/Samsung/rlottie/issues/484

**Comment by kisvegabor** [comment]
@ajsb85 
Great! I've just updated the project to work with the latest LVGL version (v8). See the README for the instructions.

What is your goal?

To make lv_lib_rlottie easier to use I think it'd be important to make it work without CMake.

**Comment by ajsb85** [comment]
I will keep in mind remove CMake
https://github.com/Samsung/rlottie/blob/master/CMakeLists.txt

I am waiting for my Nscreen32 to start contributing.

BTW could you notify them to mention the library here: https://lottiefiles.com/integrations

To get more visibility with the community.

**Comment by kisvegabor** [comment]
I haven't talked with the developers of Samsung/rlottie yet, but of course, I can mention it in the issue you have opened. 
(Done [here](https://github.com/Samsung/rlottie/issues/484#issuecomment-853925524))

**Comment by Flo082002** [comment]
Hi,
are there any updates?

**Comment by Andrisetianabrata** [comment]
Any update?

**Comment by kisvegabor** [comment]
This docs might help: https://docs.lvgl.io/master/libs/rlottie.html#esp-idf-example
