### ISSUE TITLE
More control on the animation

### ISSUE THREAD

**Issue by X-Ryl669** [lvgl/lv_lib_rlottie#4]
Would it be possible to add a bit more control to the animation. Like pausing, going to a specific frame, playing backward and so on ?
Everything seems to be done in the timer's callback, so I guess an enum and a parameter structure would be enough to add everything needed:
```cpp
enum AnimationControl
{  
   Forward,
   Pause,
   GoTo,
   Backward,
};

uint16_t parameter;

// In timer:
    lv_rlottie_t * rlottie = (lv_rlottie_t *) obj;
    switch(rlottie->control) {
      case Forward:
    if (rlottie->current_frame == rlottie->total_frames)
        rlottie->current_frame = 0;
    else
        ++rlottie->current_frame;
     break;
     case Pause: break;
     case GoTo: rlottie->current_frame = parameter; rlottie->control = Pause; break;
     case Backward: 
    if (rlottie->current_frame == 0)
        rlottie->current_frame = rlottie->total_frames - 1;
    else
        --rlottie->current_frame;
   break;
    }

    lottie_animation_render(
            rlottie->animation,
            rlottie->current_frame,
            rlottie->allocated_buf,
            rlottie->imgdsc.header.w,
            rlottie->imgdsc.header.h,
            rlottie->scanline_width
    );
```

**Comment by X-Ryl669** [comment]
Or even better, add a callback on specific frame position event ? 
To be informed when the animation is done playing for example.

**Comment by kisvegabor** [comment]
Sounds useful but I'd rather use API functions like:
```c
lv_rlottile_set_current_frame(rlottie, 25); //or < 0 to start from the last frame
lv_rlottile_set_playmode(rlottile, FORWARD/BACKWARD/PAUSE/PLAY/ | LOOP)
```

> Or even better, add a callback on specific frame position event ?


`lv_gif` sends `LV_EVENT_READY` when the animation is ready. It looks good here too. What do you think?

**Comment by X-Ryl669** [comment]
See https://github.com/lvgl/lvgl/pull/2857 for my attempt at fixing this.

**Comment by kisvegabor** [comment]
Can we close this?
